"use client";

import * as React from "react";
import { toast } from "sonner";
import { CloudServerIcon, Delete02Icon, LinkSquare02Icon, RefreshIcon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { PageHeader } from "@/components/dashboard/page-header";
import { ApiError } from "@/lib/api/client";
import { approveConnectedMachine, deleteConnectedMachine, disconnectConnectedMachine, getConnectedMachineOverview, listConnectedMachines } from "@/lib/api/connected-machines";
import type { ConnectedMachine, ConnectedMachineOverview } from "@/lib/api/types";

export default function ConnectedMachinesPage() {
  const [items, setItems] = React.useState<ConnectedMachine[]>([]); const [overview, setOverview] = React.useState<ConnectedMachineOverview>(); const [loading, setLoading] = React.useState(true); const [code, setCode] = React.useState(""); const [busy, setBusy] = React.useState<string>();
  const refresh = React.useCallback(async () => { setLoading(true); try { const [machines, usage] = await Promise.all([listConnectedMachines(), getConnectedMachineOverview()]); setItems(machines); setOverview(usage); } catch (error) { toast.error("Couldn't load connected machines.", { description: error instanceof ApiError ? error.message : "Something went wrong." }); } finally { setLoading(false); } }, []);
  React.useEffect(() => { void refresh(); }, [refresh]);
  async function approve() { setBusy("approve"); try { await approveConnectedMachine(code.trim()); setCode(""); toast.success("Machine approved."); await refresh(); } catch (error) { toast.error("Couldn't approve machine.", { description: error instanceof ApiError ? error.message : "Check the pairing code and available seats." }); } finally { setBusy(undefined); } }
  async function act(id: string, kind: "disconnect" | "delete") { setBusy(id + kind); try { if (kind === "disconnect") await disconnectConnectedMachine(id); else await deleteConnectedMachine(id); toast.success(kind === "disconnect" ? "Machine disconnected." : "Machine deleted."); await refresh(); } catch (error) { toast.error(`Couldn't ${kind} machine.`, { description: error instanceof ApiError ? error.message : "Something went wrong." }); } finally { setBusy(undefined); } }
  const includedPercent = overview?.included_bytes ? Math.min(100, Math.round((overview.consumed_included_bytes / overview.included_bytes) * 100)) : 0;
  return <><PageHeader eyebrow="Workspace" title="Connected machines" description="Enroll a macOS or Linux computer through Paperboat without moving its workspace to the cloud." />
    {!loading && overview ? <><section className="mb-6 grid gap-px overflow-hidden rounded-2xl border bg-border shadow-xs/5 sm:grid-cols-3"><div className="bg-background p-4"><p className="text-xs text-muted-foreground">Seats</p><p className="mt-1 font-heading text-2xl font-semibold">{overview.occupied_seats} / {overview.seat_quantity}</p><p className="mt-1 text-xs text-muted-foreground">{overview.available_seats} available</p></div><div className="bg-background p-4"><p className="text-xs text-muted-foreground">Included bandwidth</p><p className="mt-1 font-heading text-2xl font-semibold">{includedPercent}%</p><div className="mt-2 h-1.5 bg-muted"><div className="h-full bg-primary" style={{ width: `${includedPercent}%` }} /></div></div><div className="bg-background p-4"><p className="text-xs text-muted-foreground">Paid bandwidth remaining</p><p className="mt-1 font-heading text-2xl font-semibold">{formatBytes(overview.paid_topup_remaining_bytes)}</p><p className="mt-1 text-xs text-muted-foreground">{overview.entitlement_state}</p></div></section>{overview.bootstrap_command ? <pre className="mb-6 overflow-x-auto border bg-muted/30 p-3 text-xs"><code>{overview.bootstrap_command}</code></pre> : null}</> : null}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="grid gap-4 md:grid-cols-2">{loading ? <div className="col-span-full flex justify-center py-16"><Spinner className="size-6" /></div> : items.length === 0 ? <Card className="col-span-full"><CardContent className="flex min-h-56 flex-col items-center justify-center gap-3 text-center"><HugeiconsIcon icon={CloudServerIcon} className="size-7 text-muted-foreground" /><p className="font-heading text-xl font-semibold">No connected machines</p><p className="max-w-md text-sm text-muted-foreground">Run the connector on a computer, then enter its pairing code here.</p></CardContent></Card> : items.map((machine) => <Card key={machine.id}><CardHeader><CardTitle className="font-heading text-base">{machine.display_name}</CardTitle><CardDescription className="font-mono text-xs">{machine.platform} / {machine.architecture}</CardDescription></CardHeader><CardContent className="space-y-2 text-sm"><p className="truncate text-muted-foreground">{machine.workspace_root}</p><p><span className={machine.online ? "text-primary" : "text-muted-foreground"}>{machine.online ? "Online" : machine.state}</span> <span className="text-muted-foreground">· seat {machine.seat_state}</span></p></CardContent><CardFooter className="gap-2"><Button size="sm" variant="outline" disabled={busy === machine.id + "disconnect"} onClick={() => void act(machine.id, "disconnect")}><HugeiconsIcon icon={LinkSquare02Icon} />Disconnect</Button><Button size="icon-sm" variant="ghost" aria-label={`Delete ${machine.display_name}`} disabled={busy === machine.id + "delete"} onClick={() => void act(machine.id, "delete")}><HugeiconsIcon icon={Delete02Icon} /></Button></CardFooter></Card>)}</section>
      <aside><Card><CardHeader><CardTitle className="font-heading text-base">Approve pairing</CardTitle><CardDescription>Enter the code shown by the connector.</CardDescription></CardHeader><CardContent className="space-y-3"><Input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="ABCD1234" className="font-mono tracking-[0.12em]" maxLength={32} /></CardContent><CardFooter><Button className="w-full" disabled={!code.trim() || busy === "approve"} onClick={() => void approve()}>{busy === "approve" ? <Spinner /> : <HugeiconsIcon icon={LinkSquare02Icon} />}Approve machine</Button></CardFooter></Card><Button className="mt-4 w-full" variant="ghost" onClick={() => void refresh()}><HugeiconsIcon icon={RefreshIcon} />Refresh</Button></aside></div></>;
}

function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB", "TB"]; let value = bytes / 1024; let index = 0; while (value >= 1024 && index < units.length - 1) { value /= 1024; index += 1; } return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[index]}`; }
